# Generated by Django 3.0.3 on 2020-03-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sicilian Pizza', 'Sicilian Pizza'), ('regular Pizza', 'Regular Pizza')], max_length=64)),
                ('large', models.FloatField()),
                ('small', models.FloatField()),
            ],
        ),
    ]
