# Generated by Django 3.0.3 on 2020-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pasta_salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pasta', 'pasta'), ('salads', 'salads')], max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='subs_platters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('platters', 'DinnerPlatters'), ('sub', 'sub')], max_length=64)),
                ('dish_name', models.CharField(max_length=64)),
                ('large', models.FloatField()),
                ('small', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topp_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='topp',
            field=models.CharField(choices=[('sicilian Pizza', 'Sicilian Pizza'), ('regular Pizza', 'Regular Pizza')], default='regular Pizza', max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('chesee', 'chesee'), ('1 toppings', '1 toppings'), ('2 toppings', '2 toppings'), ('3 toppings', '3 toppings')], default='chesse', max_length=64),
        ),
    ]
