# Generated by Django 3.0.3 on 2020-03-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200309_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta_salads',
            name='plate_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='subs_platters',
            name='type',
            field=models.CharField(choices=[('platters', 'DinnerPlatters'), ('sub', 'sub')], default='platters', max_length=64),
        ),
    ]
