# Generated by Django 3.0.3 on 2020-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200309_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topp',
            field=models.CharField(choices=[('chesee', 'chesee'), ('1 toppings', '1 toppings'), ('2 toppings', '2 toppings'), ('3 toppings', '3 toppings')], default='chesee', max_length=64),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('sicilian Pizza', 'Sicilian Pizza'), ('regular Pizza', 'Regular Pizza')], default='regular Pizza', max_length=64),
        ),
    ]
