# Generated by Django 3.0.3 on 2020-03-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200315_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs_platters',
            name='small',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
