# Generated by Django 3.0.3 on 2020-03-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200328_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='pizza_size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='platter_size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='sub_size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='pizza_topping',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
